### ISSUE TITLE
How can I use dynamic schemas?

### ISSUE THREAD

**Issue by anhnmt** [connectrpc/vanguard-go#104]
I have a proto file and gprc client address localhost:8080

How can I connect to gprc client using the above proto file without having to generate .pb.go or .connect.go files?

This mechanism of action may look like this: https://docs.konghq.com/hub/kong-inc/grpc-gateway/how-to/

Also I quite enjoy using this library, thank you for creating this wonderful library 😁

**Comment by emcfarlane** [comment]
Hey @anhnmt thanks for trying out the library! For dynamic protobuf files you can create the service with [`vanguard.NewServiceWithSchema`](https://pkg.go.dev/connectrpc.com/vanguard#NewServiceWithSchema). See [here](https://pkg.go.dev/connectrpc.com/vanguard#section-readme) for details on how to dynamically load protobufs. 

To clarify is it a gRPC server on localhost:8080? To create a reverse proxy you could setup the proxy server as:
```go
var schema protoreflect.ServiceDescriptor // Loaded dynamically
remote, err := url.Parse("localhost:8080")
if err != nil {
	log.Fatal(err)
}
proxy := httputil.NewSingleHostReverseProxy(remote)
transcoder = vanguard.NewTranscoder(
	[]*vanguard.Service{
		 vanguard.NewServiceWithSchema(schema, proxy)
	},
)
```

**Comment by jhump** [comment]
@anhnmt, hi! Glad you are finding this repo valuable!

For a little more info on obtaining descriptors, to use with `vanguard.NewServiceWithSchema`, you'll do something like this:

1. Read the configured schema file. A schema file will usually be a binary-encoded `google.protobuf.FileDescriptorSet` message. You'll unmarshal the file contents into a new message of that type (`*descriptorpb.FileDescriptorSet` in the Go runtime). From there, you can create a `*protoregistry.Files` using [`protodesc.NewFiles`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc#NewFiles) and then create a type resolver using [`dynamicpb.NewTypes`](https://pkg.go.dev/google.golang.org/protobuf@v1.31.0/types/dynamicpb#NewTypes).
   * Note you could also retrieve the schema using [gRPC Reflection](https://pkg.go.dev/connectrpc.com/grpcreflect#NewClient) or a [Buf Schema Registry](https://buf.build/bufbuild/reflect).
2. Find the relevant services using [`files.FindDescriptorByName`](https://pkg.go.dev/google.golang.org/protobuf@v1.31.0/reflect/protoregistry#Files.FindDescriptorByName). You can then type-assert the result to a `protoreflect.ServiceDescriptor` and provide to `vanguard.NewServiceWithSchema`.
   * You'll also want to provide the type resolver as an option, via `vanguard.WithTypeResolver(types)`. This allows for the same schema file to be consulted when marshaling and un-marshaling extensions and `google.protobuf.Any` messages.

**Comment by anhnmt** [comment]
@emcfarlane I use httputil.NewSingleHostReverseProxy but it seems it only reverses HTTP proxies, gRPC does not.
Do you have any method to reverse gRPC proxy?

**Comment by jhump** [comment]
@anhnmt, gRPC uses HTTP under the hood. If you are having an issue, it is likely due to use of HTTP 1.1, whereas gRPC requires HTTP/2. If you are not using TLS (where the HTTP/2 protocol can be negotiated during the TLS handshake), then you need to be using "HTTP/2 over clear text", also called "H2C". There is more detail in the Connect docs, since this is also necessary to use the gRPC protocol with the connect-go module: https://connectrpc.com/docs/go/deployment/#h2c

In particular, you'd need to wrap your reverse proxy handler using `h2c.NewHandler` as in the code snippet in that link, if your proxy server accepts gRPC requests without TLS. And you need to set the `Transport` field of the `httputil.ReverseProxy` to a transport implementation supports H2C. The link above shows an example of creating an `http2.Transport` that works over plaintext.

**Comment by anhnmt** [comment]
@jhump, I used h2c but it seems I made a mistake in some step so I still can't connect to gRPC
Here is my source code: https://github.com/anhnmt/gprc-dynamic-proto/blob/main/cmd/dynamic/main.go

**Comment by anhnmt** [comment]
@emcfarlane

```go
proxy.Transport = &http2.Transport{AllowHTTP: true}
```
I also tried your method but encountered some other problems, for example:
- REST: 502 Bad Gateway
- gRPC: 14 UNAVAILABLE

**Comment by anhnmt** [comment]
@emcfarlane 
Thank you very much 😁
Also, can you give me some feedback on optimizing this part?

```go
import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"path/filepath"
	"time"

	"connectrpc.com/vanguard"
	"github.com/jhump/protoreflect/desc/protoparse"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
)

	googleapis := []string{
		"google/api/annotations.proto",
		"google/api/http.proto",
		"google/protobuf/descriptor.proto",
	}

	files := append(googleapis, "user/v1/user.proto")

	p := protoparse.Parser{
		ImportPaths: []string{
			"proto",
			"googleapis",
		},
		Accessor: func(filename string) (io.ReadCloser, error) {
			return ReadFileContent(filename)
		},
	}

	fds, err := p.ParseFiles(files...)
	if err != nil {
		log.Err(err).Msg("could not parse given files")
		return
	}

	fileDescriptors := make([]*descriptorpb.FileDescriptorProto, 0)
	for _, fd := range fds {
		fileDescriptors = append(fileDescriptors, fd.AsFileDescriptorProto())
	}

	newFiles, err := protodesc.NewFiles(&descriptorpb.FileDescriptorSet{
		File: fileDescriptors,
	})
	if err != nil {
		log.Err(err).Msg("could not parse given files")
		return
	}

	types := dynamicpb.NewTypes(newFiles)

	name, err := newFiles.FindDescriptorByName("user.v1.UserService")
	if err != nil {
		return
	}
	serviceDesc := name.ParentFile().Services().ByName("UserService")
```

**Comment by emcfarlane** [comment]
The use of `protoparse` is really interesting! If you want to parse the descriptors up front you could use buf's images. See the docs [here](https://buf.build/docs/reference/images#what-are-buf-images?). Then build the image up front and include the filedescriptor sets dynamically:`buf build -o users.binpb`. @jhump will have better advice!

A bug I noticed in the proto. The option in `users.proto`:
```
    option (google.api.http) = {get: "/v1/users/{page=**}"};
```
Should be `{page=*}` as `**` will never be able to be unmarshalled into the page int32 field. There does look like an issue with stacking multiple `Transcoder` instances and error handling. 
1. Directly curling the server: `curl localhost:8080/v1/users/1/123`
```json
{"code":3,"message":"invalid parameter \"page\" invalid character '/' after top-level value","details":[]}
```
2.  Proxying the server: `curl localhost:8000/v1/users/1/123`
```json
{"code":2, "message":"response uses incorrect codec: expecting \"json\" but instead got \"?\"", "details":[]}
```

**Comment by anhnmt** [comment]
@jhump, I used protocompile and got the following error, while github.com/jhump/protoreflect did not get this case

My source code: https://github.com/anhnmt/gprc-dynamic-proto/blob/protocompile/cmd/dynamic/main.go

```
panic: invalid type: got *dynamicpb.Message, want *annotations.HttpRule

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.(*messageConverter).GoValueOf(0xc0000b7ab0, {{}, 0x119f640?, 0xc000107ac0?, 0x128ee28?})
        C:/Users/ANHNMT/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/impl/convert.go:457 +0x408
google.golang.org/protobuf/internal/impl.(*ExtensionInfo).InterfaceOf(0x1651ee0?, {{}, 0x119f640?, 0xc000107ac0?, 0x1651f00?})
        C:/Users/ANHNMT/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/impl/extension.go:102 +0x5a
google.golang.org/protobuf/proto.GetExtension({0x1287140?, 0xc000322360?}, {0x128ee28, 0x1651ee0})
        C:/Users/ANHNMT/go/pkg/mod/google.golang.org/protobuf@v1.31.0/proto/extension.go:45 +0x9b
connectrpc.com/vanguard.getHTTPRuleExtension({0x1290e88?, 0xc00013e6c0?})
        C:/Users/ANHNMT/go/pkg/mod/connectrpc.com/vanguard@v0.1.0/protocol_http.go:342 +0x66
connectrpc.com/vanguard.(*Transcoder).registerMethod(0xc00013e8a0, {0x1286360?, 0xc000127428}, {0x1290e88, 0xc00013e6c0}, 0xc000107b40)
        C:/Users/ANHNMT/go/pkg/mod/connectrpc.com/vanguard@v0.1.0/transcoder.go:204 +0x2e5
connectrpc.com/vanguard.(*Transcoder).registerService(0xc00013e8a0, 0xc000367ee8, {{0x128c538, 0xc0000403f0}, 0xc00052fd40, 0xc00052fce0, 0xc00052fd10, {0x11b9b31, 0x5}, 0xffffffff, ...})
        C:/Users/ANHNMT/go/pkg/mod/connectrpc.com/vanguard@v0.1.0/transcoder.go:127 +0x6f8
connectrpc.com/vanguard.NewTranscoder({0xc000367e58, 0x1, 0xb?}, {0x0, 0x0, 0x6?})
        C:/Users/ANHNMT/go/pkg/mod/connectrpc.com/vanguard@v0.1.0/vanguard.go:131 +0x628
main.main()
        C:/Golang/gprc-dynamic-proto/cmd/dynamic/main.go:157 +0x6bc

Process finished with the exit code 2
```

**Comment by jhump** [comment]
@anhnmt, ah, right. Sorry, I forgot about the HTTP annotations. It is indeed expected that they are dynamic extensions from the compiler (since the compiler's version of the message definition could differ from the version linked into the calling program).

Seems like a good addition to protocompile would be a helper to address that, or maybe even a compiler option so that you don't have to do anything as a post-process. The helper or option would basically do the same thing that protoparse does, which is to re-parse custom options using `protoregistry.GlobalTypes` as the resolver.

**Comment by jhump** [comment]
@rauanmayemir, @anhnmt, I think #179 should remedy the panics that you've encountered, without having to do a bunch of extra plumbing/descriptor processing in the calling application.
