### ISSUE TITLE
How to collect rules from proto descriptors

### ISSUE THREAD

**Issue by rauanmayemir** [connectrpc/vanguard-go#145]
How do I go about collecting `google.api.http` annotations from dynamic proto schema?
I tried to check examples, but they add HttpRules manually.

P.S: Should github discussions be enabled for this kind of questions?

**Comment by jhump** [comment]
What do you mean by "collecting"? If you are encountering an issue with something, could you elaborate on what you're trying and what unexpected behavior you are seeing?

**Comment by rauanmayemir** [comment]
Oh, right. I want to set up gRPC-JSON transcoding for dynamic schema. I found the option `vanguard.WithRules`, but now I need to get those rules from proto schema.

**Comment by jhump** [comment]
@rauanmayemir, those are for rules that are _not_ in the schema. So if you have RPC services defined in Protobuf that did not declare any HTTP rules, you can supply them -- like "sidecar" configuration, to map RPC services to REST even if they were not originally designed for REST.

If your options are _in_ the schema, then just pass the descriptors when you create the services.

**Comment by rauanmayemir** [comment]
Understood, thanks! I want to see how it works, where exactly those routes are being set up?

**Comment by rauanmayemir** [comment]
Just found a reason this didn't work. For dynamic pb schema, I also need to pass `WithTypeResolver`.
