### ISSUE TITLE
Expose unbound query params into connect.Request via transcoded route

### ISSUE THREAD

**Issue by novabyte** [connectrpc/vanguard-go#146]
We have an API which we need to conform to which we'd like to use ConnectRPC+Vanguard on and looks a bit like [Contentful](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/inclusion/query-entries/console). Some query parameters are dynamic bsaed on the metadata of the content stored.

For example:

```
/spaces/{space_id}/environments/{environment_id}/entries?access_token={access_token}&content_type={content_type}&{attribute}[in]={value}
```

The `{attribute}` query param name itself could be `fields` or some other value known by the caller based on the content which has been stored and will be fetched. For this use case we'd like to be able to just allow unbound query params to be visible to the `connect.Request` input:

```
req.Peer().Query.Get("fields")
```

But at the moment unbound query params can either be ignored or will fail to match the route. How do we enable unbound query params to be available to the `Peer.Query` in Connect via a transcoded route with Vanguard?

**Comment by emcfarlane** [comment]
Hi @novabyte, query fields don't support maps but do support lists of values. If you were able to change the schema you could use repeated string values `?attribute=field%5Bin%5D%3Dvalue` which would be the URL escaped form of `field[in]=value` and would be served as a list of string attributes you can pass in the message.
```proto
message QueryParameters { repeated string attribute = 1 }
```
Using query parameters in connect is not a generally recognized pattern so passing unmatched URL query parameters downstream to the service is not currently supported. I'm unsure if we would be able to handle this without explicit declaring what parameters to pass through.

So a solution to conform to the given API would be to have some HTTP middleware that remaps any query parameters into a form that is representable as HTTP transcoded query parameters before being processed by vanguard. Let me know if that is helpful.

**Comment by novabyte** [comment]
@emcfarlane Thanks for the fast follow up. 🙏 

I completely agree it's an odd use case. Take a technology used to describe structured services and let them handle a unbound collection of query params which come from the caller. I have managed to find a hack which solves my use case if I add:

```go
o.request.URL.RawQuery = o.queryValues().Encode()
``` 

just before [`transcoder.go:601`](https://github.com/connectrpc/vanguard-go/blob/main/transcoder.go#L601).

Was it a specific design decision to drain the query parameters before the `http.Request` is passed onto `ServeHTTP`?

**Comment by novabyte** [comment]
@emcfarlane I think I found a more idiomatic changeset to handle our use case:

```go
discardUnknownQueryParams := op.methodConf.serviceOptions.restUnmarshalOptions.DiscardUnknownQueryParams
if !discardUnknownQueryParams {
	queryParams = op.request.URL.RawQuery
}
```

applied just after this code: https://github.com/connectrpc/vanguard-go/blob/main/protocol_rest.go#L406

@emcfarlane Would it be useful as a contribution? If so, what could I change to make it acceptable?

**Comment by novabyte** [comment]
@emcfarlane I took your advice and implemented a `http.Handler` which wraps the `Transcoder` handler and use a `UnaryInterceptorFunc` to unpack the query params and put them into `req.Peer().Query` so they can be used within service functions. Thanks for the suggestion 🙏

**Comment by emcfarlane** [comment]
Glad you found a solution! I think the issue of passing unknown query parameters to the downstream service may be something we should change. Would be open to see solutions there, but would still be hesitant in using them to alter the RPC behaviour as that goes against the proto defined contract of the service.
